# DSCI6001 1.3 Lab (Graded)

This will be a graded laboratory assignment. It should take approximately 60 minutes. If needed you can turn it in the next day.

For questions **1) - 3)**, we will work with the following matrix.   

$${\bf A} = \begin{bmatrix}
    2 & 2 & 7 \\
    3 & 4 & 1 \\
    5 & 6 & 2 \\
\end{bmatrix}$$

**1) Matrix rank**  

Use Gauss elimination to produce the row echelon form of Matrix $\mathbf{A}$. What is the rank of $\mathbf{A}$? Use [numpy.linalg.matrix_rank](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.matrix_rank.html) to check your answer.

# Row echelon form
[[2, 2, 7],
[0 ,2, -19],
[0, 0, -14]]

In [4]:


import numpy as np
A = np.array([[2,2],
                [3,4],
                [5,6]])
B = np.array([[7],
                [1],
                [2]])
C = np.array([[2,2,7],
                [3,4,1],
                [5,6,2]])

print(np.linalg.matrix_rank(C))
#print(np.linalg.solve(A,B))


3


**2) Determinant**  

Calculate the determinant of $\mathbf{A}$ by hand, then use [numpy.linalg.det](https://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.linalg.det.html) to check your answer.

In [37]:
#Determinant of A
#1) 2*(4 * 2)-(1*6)) - 2*(3*2)-(1*5)) + 7 ( 3*6 - (4*5)) = -12 

In [6]:
np.linalg.det(C)

-11.999999999999979

**3) Matrix inversion**  

Is matrix $\mathbf{A}$ invertible? If so, use [numpy.linalg.inv](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html) to find its inverse.

If a matrix is invertible then determinant does not equal zero.
This matrix is invertible

**4) Programming practice**  

In yesterday's lecture you were assigned to solve the following problems from the textbook:

Problem Set 7.3: 1, 3, 5, 7, 11, 13.

1. Create Numpy arrays to represent the 6 linear systems you solved by hand yesterday in Problem Set 7.3. 

2. Solve all 6 systems using Numpy. 

Extra Credit: Store your linear systems as follows: a list of the arrays of the 6 coeffiecient matrices, and a second list, of the dependent parameters (vector $\mathbf{b}$ from the notes) of each system. Zip these two lists together. Build a loop to process these arrays, built around the following code snippet. Add code to print the solutions more elegantly. Add code to handle exceptions gracefully. 

In [32]:
#This is using the 9th edition of the textbook
one_variables=np.array([[5,-2],
           [-1,4]])
one_dependents = np.array([[20.9],
                       [-19.3]])
three_variables= np.array([[.5,3.5],
                      [-1,5.0]])
three_dependents = np.array([[5.7],
                       [-7.8]])
five_variables=np.array([[.8,1.2,-.6],
                     [2.6,0,1.7],
                     [4.0,-7.3,-1.5]])
five_dependents = np.array([[-7.8],
                       [15.3],
                        [1.1]])
seven_variables = np.array([[0,1,1],
                           [0,4,6],
                           [1,1,1]])

seven_dependents = np.array([[-2],
                             [-12],
                             [2]])
nine_variables = np.array([[0,4,4],
                          [3,-11,2],
                          [6,-17,1]])
nine_dependents = np.array([[24],
                          [-6],
                          [18]])

eleven_variables = np.array([[2,-1,3],
                            [-4,2,-6]])
eleven_dependents = np.array([[-1],
                             [2]])
thirteen_variables = np.array([[0,1,1,-2],
                             [-4,-1,-1,2],
                             [-2,3,3,-6]])
thirteen_dependents = np.array([[0],
                               [-4],
                               [-2]])


system_variables = [one_variables,three_variables,five_variables,seven_variables,nine_variables,eleven_variables,thirteen_variables]
system_dependents = [one_dependents,three_dependents,five_dependents,seven_dependents,nine_dependents,eleven_dependents,thirteen_dependents]


In [39]:

for count,(item, solution) in enumerate(zip(system_variables,system_dependents)):

        try:
            print(np.linalg.solve(item,solution),'Solved the system for problem: ', (count)*2+1)
        except:
            print('There is no solution for problem:',(count)*2+1)
            print('This set of variables',item,' with these solutions', solution,)
            
        
        

[[ 2.5]
 [-4.2]] Solved the system for problem:  1
[[ 9.3]
 [ 0.3]] Solved the system for problem:  3
[[  8.10462808e-16]
 [ -2.00000000e+00]
 [  9.00000000e+00]] Solved the system for problem:  5
[[ 4.]
 [ 0.]
 [-2.]] Solved the system for problem:  7
[[ 20.]
 [  6.]
 [  0.]] Solved the system for problem:  9
There is no solution for problem: 11
This set of variables [[ 2 -1  3]
 [-4  2 -6]]  with these solutions [[-1]
 [ 2]]
There is no solution for problem: 13
This set of variables [[ 0  1  1 -2]
 [-4 -1 -1  2]
 [-2  3  3 -6]]  with these solutions [[ 0]
 [-4]
 [-2]]


In [13]:
for n, (a1, b1) in enumerate(zip(system_variables, system_dependents)):
    print(n,'count')
    print(a1,'a1')
    print(b1,'b1')

0 count
[[ 5 -2]
 [-1  4]] a1
[[ 20.9]
 [-19.3]] b1
1 count
[[ 0.5  3.5]
 [-1.   5. ]] a1
[[ 5.7]
 [-7.8]] b1
2 count
[[ 0.8  1.2 -0.6]
 [ 2.6  0.   1.7]
 [ 4.  -7.3 -1.5]] a1
[[ -7.8]
 [ 15.3]
 [  1.1]] b1
3 count
[[0 1 1]
 [0 4 6]
 [1 1 1]] a1
[[-2 12  2]] b1
4 count
[[  0   4   4]
 [  3 -11   2]
 [  6 -17   1]] a1
[[24]
 [-6]
 [18]] b1
5 count
[[ 2 -1  3]
 [-4  2 -6]] a1
[[-1]
 [ 2]] b1
6 count
[[ 0  1  1 -2]
 [-4 -1 -1  2]
 [-2  3  3 -6]] a1
[[ 0]
 [-4]
 [-2]] b1
