# RAT 7.1


1) Write the change of basis matrix M from the standard basis in $\mathbb{R}^2$ to the new basis $\{\begin{bmatrix}3\\1\end{bmatrix},\begin{bmatrix}-2\\1\end{bmatrix}\}$



2) Given the two bases
$S = \{\begin{bmatrix}2\\3\end{bmatrix},\begin{bmatrix}1\\4\end{bmatrix}\}$, $T = \{\begin{bmatrix}0\\2\end{bmatrix},\begin{bmatrix}-1\\5\end{bmatrix}\}$

and the vector $v_S = \begin{bmatrix}-2\\6\end{bmatrix}$

calculate $v_T$.


# 1) To solve for the change of basis, create an equation to convert between.


In [66]:
#Pick a point in the basis

#Point = (2,5)

#Take new basis, multipled by the point


import numpy as np
new_basis = np.array([[3,-2],
                          [1,1]])
point = np.array([[2],
            [5]])

new_basis.dot(point)

array([[-4],
       [ 7]])

In [7]:
#Therefore, new basis -> new basis is (-4,7)T

In [8]:
#Next, take standard basis multipled by your point

In [67]:
standard_basis = np.array([[1,0],
                          [0,1]])

standard_basis.dot(point)

array([[2],
       [5]])

In [10]:
#Standard basis -> point is (2,3)T

# Next take your basis change matrix, multipled by the new basis and set equal to your standard basis

In [11]:
# Our equation is, change of basis matrix .dot ( -4,7).T = (2,5).T

In [74]:
original_basis_vector = np.array([[-4],
                                 [7]])
new_basis_vector = np.array([[2],
                            [5]])


In [75]:
original_basis_vector.dot(new_basis_vector.T)

array([[ -8, -20],
       [ 14,  35]])

In [78]:
change_of_basis_matrix = (new_basis_vector).dot(original_basis_vector.T)
change_of_basis_matrix

array([[ -8,  14],
       [-20,  35]])

In [92]:
change_of_basis_matrix.dot(original_basis_vector)/65

array([[ 2.],
       [ 5.]])

# Our change of basis change matrix is [-8,-20] .T  [14,35].T

5.0

2) Given the two bases
$S = \{\begin{bmatrix}2\\3\end{bmatrix},\begin{bmatrix}1\\4\end{bmatrix}\}$, $T = \{\begin{bmatrix}0\\2\end{bmatrix},\begin{bmatrix}-1\\5\end{bmatrix}\}$

and the vector $v_S = \begin{bmatrix}-2\\6\end{bmatrix}$

calculate $v_T$.


In [61]:
s = np.array([[2,1],
             [3,4]])

t= np.array([[0,-1],
            [2,5]])

vs = np.array([[-2],
               [6]])

In [62]:
s.dot(vs)

array([[ 2],
       [18]])

In [63]:
np.linalg.solve(t,s.dot(vs))

array([[ 14.],
       [ -2.]])

# Vt = [14,-2].T