# DSCI6001 1.2 Lab (Graded)

This will be a graded laboratory assignment. 

#### 1) Use Numpy to create and store the matrices $A, B, C, D$ and vectors $u, v$.

$$
{\bf A}=
\begin{bmatrix}
3 & 0 & 4 \\
-1 & 2 & 2 \\
6 & 5 & -4
\end{bmatrix},\quad
{\bf B}=
\begin{bmatrix}
0 & -5 & -3 \\
-5 & 2 & 4 \\
-3 & 4 & 0
\end{bmatrix},\quad
{\bf C}=
\begin{bmatrix}
0 & 2 \\
2 & 4 \\
1 & 3
\end{bmatrix},\quad
{\bf D}=
\begin{bmatrix}
6 & 1 \\
-4 & 7 \\
-8 & 3
\end{bmatrix}
$$

$$
\textbf{u}=
\begin{bmatrix}
2 \\
0 \\
1
\end{bmatrix},\quad
\textbf{v}=
\begin{bmatrix}
-4 \\
9 \\
2
\end{bmatrix}
$$

In [52]:
import numpy as np
A = np.array([[3,0,4],
             [-1,2,2],
             [6,5,-4]])

B=np.array([[0,-5,-3],
           [-5,2,4],
           [-3,4,0]])

C=np.array([[0,2],
           [2,4],
           [1,3]])
D=np.array([[6,1],
            [-4,7],
            [-8,3]])
u=np.array([[2],
           [0],
           [1]])
v = np.array([[-4],
             [9],
             [2]])


#### 2) Use Python to determine their dimensions.

In [53]:
print(A.shape,"shape of A")
print(B.shape,"shape of B")
print(C.shape, "shape of C")
print(D.shape, "shape of D")
print(u.shape, "shape of U")
print(v.shape, "shape of V")


(3, 3) shape of A
(3, 3) shape of B
(3, 2) shape of C
(3, 2) shape of D
(3, 1) shape of U
(3, 1) shape of V


#### 3) Calculate:
* $4C+2D$
* $2(A+B)$
* $u-v$

In [73]:
print(" 4C+2D\n ",4*C+2*D)
print(2*(A+B),"2(A+B)")
print(u-v,"u-v")

 4C+2D
  [[ 12  10]
 [  0  30]
 [-12  18]]
[[  6 -10   2]
 [-12   8  12]
 [  6  18  -8]] 2(A+B)
[[ 6]
 [-9]
 [-1]] u-v


#### 4) Does $(\textit{A}\textit{B})^{T}$ = $\textit{B}^{T}\textit{A}^{T}$? Produce an assertion that checks for this.

In [72]:
print(B.T*A.T)
print(B.T.dot(A.T))
print(A)
print(B)

assert(((A.dot(B.T)).all()) == ((B.T).dot((A.T)).all())) ### Check to see if the matrix A and B and equal 


[[  0   5 -18]
 [  0   4  20]
 [-12   8   0]]
[[-12 -16 -13]
 [  1  17 -36]
 [ -9  11   2]]
[[ 3  0  4]
 [-1  2  2]
 [ 6  5 -4]]
[[ 0 -5 -3]
 [-5  2  4]
 [-3  4  0]]


#### 5) Solve the linear system below by hand, then check your answers in Python using [numpy.linalg.solve](https://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.linalg.solve.html).

$$
\begin{align}
x + y + 2z & = 3 \\
3x + 4y + 8z & = 10 \\
-2x + 2y + z & = 7
\end{align}
$$


In [56]:
coefficient_matrix = np.array([[1,1,2],
                              [3,4,8],
                              [-2,2,1]])
dependent_matrix = np.array([[3],
                            [10],
                            [7]])


In [57]:
np.linalg.solve(coefficient_matrix,dependent_matrix)

array([[ 2.],
       [ 7.],
       [-3.]])