# Matrix Inverse using Gauss Jordan elimination

In [1]:
import numpy as np
import pandas as pd

In [132]:
def gauss_jordan_inverse(A):
    
    number_of_rows = len(A)
    number_of_columns = len(A[0])
    identity = np.identity(number_of_rows)
    
    
    for i in range(number_of_columns): ## go through every column
        
            pass
        
    for j in range(number_of_rows): ## go through every row
            
        pivot = max(abs(A[:,i])) 
        pivot_row_index = [item for item in range(number_of_rows) if pivot in A[item]] 
        ## test to see if the row index of the largest number equals the row we are on
            
        print(pivot_row_index,'pivot row index')
        if pivot_row_index != j:
            #print(A[j],'A[j]')
            #print(A[i],'A[i]')
            #print(A[j],'j')
            #print(A[pivot_row_index],'pivot row index')
                
            A[j],A[pivot_row_index] = A[pivot_row_index],A[j].copy()
                
            print(A, '-----------')
        
        print(pivot,'pivot')    
        
    return A

In [144]:
B = np.array([[1,2,3],
             [23,43,23],
             [1,2,345345]])


In [145]:
gauss_jordan_inverse(B)

[2] pivot row index
[[     1      2 345345]
 [    23     43     23]
 [     1      2      3]] -----------
345345 pivot
[0] pivot row index
[[    23     43     23]
 [     1      2 345345]
 [     1      2      3]] -----------
345345 pivot


array([[    23,     43,     23],
       [     1,      2, 345345],
       [     1,      2,      3]])

# Built in Numpy inverse method

In [192]:
###Numpy solutions

import timeit
import numpy as np

def numpy_inv_time(A):
    shape = np.shape(A)
    if shape[0]==shape[1]:
    
        #print(timeit.timeit('np.linalg.inv(A)',number=100))
        
        return np.linalg.inv(A)
       
    else:
        return ' not a square matrix '

In [194]:
def wrapper(func, *args, **kwargs):
    def wrapped():
        return func(*args, **kwargs)
    return wrapped

In [195]:
matrix_wrapper = wrapper(numpy_inv_time,B) ##need to wrap together the matrix and the function in order to time it

timeit.timeit(matrix_wrapper,number=100)

0.0024997789987537544

In [221]:
for item in range(0,100):
    matrix = np.random.randint(0,100, size = (item,item))
    matrix_wrapper = wrapper(numpy_inv_time,matrix)
    print('Matrix of size {} takes {} seconds to find the inverse using numpys inverse method'.format(item,timeit.timeit(matrix_wrapper,number=100)))

    

Matrix of size 0 takes 0.0005080500013718847 seconds to find the inverse using numpys inverse method
Matrix of size 1 takes 0.0019623089974629693 seconds to find the inverse using numpys inverse method
Matrix of size 2 takes 0.0016835269998409785 seconds to find the inverse using numpys inverse method
Matrix of size 3 takes 0.0016170790004252922 seconds to find the inverse using numpys inverse method
Matrix of size 4 takes 0.001722404998872662 seconds to find the inverse using numpys inverse method
Matrix of size 5 takes 0.0018827099993359298 seconds to find the inverse using numpys inverse method
Matrix of size 6 takes 0.0022107999975560233 seconds to find the inverse using numpys inverse method
Matrix of size 7 takes 0.002258929998788517 seconds to find the inverse using numpys inverse method
Matrix of size 8 takes 0.0020989500007999595 seconds to find the inverse using numpys inverse method
Matrix of size 9 takes 0.0023428370004694443 seconds to find the inverse using numpys inverse

array([[  6.66666667e-01,   8.01138195e-05,  -1.43334134e+01],
       [ -3.33333333e-01,  -4.44004301e-05,   7.66671107e+00],
       [ -0.00000000e+00,   2.89568022e-06,  -2.89568022e-06]])