# DSCI 6001 5.3 Lab 

## QR Factorization II


## Practical application of the QR algorithm: Stabilized Gram-Schmidt 


Because the GS mapping is so onerous (and numerically unstable) to calculate, and the results so difficult to compare,
there are several ways in which this problem is addressed. The first is by creating the **Modified or Stabilized Gram Schmidt** algorithm, which creates a different Gram-Schmidt factorization (usually in-place) by using normalized vectors as the input in all parts of the computation, making numerical errors much smaller by comparison:

#### Modified Gram-Schmidt


$for\ i\ in\ \{1 \cdots k\}$

  $\ \ \ \ \ for\ j\ in\ \{1 \cdots j-1\}$
  
   $\ \ \ \ \ \ \ \  v_j = v_j - \text{proj}_{v_{i}}v_{j}$
   
   $\ \ \ \ \   v_j = v_{j}/\|v_{j}\|$
            

### TASK:

Implement the MGS algorithm using the below code stub.


In [1]:
import numpy as np

In [173]:
def stabilized_gram_schmidt(a):
        print(a)
        a=a
        a_t = a.T.astype(float)
        print(a_t)
        
        def projection(c2,c1): return (c2.dot(c1)/(c1.dot(c1)))*c1
        
        for j, row in enumerate(a_t):
            ## a is transposed
            if j ==0:
                #print(a[j],'first a j')
                #print(a_t[j],'a transposed j')
                #print ((a_t[j]/np.linalg.norm(a_t[j])) , 'norm of first row')
                
                a_t[j]=(a_t[j]/np.linalg.norm(a_t[j])) ### normalzie the first vector
                
                #print(a_t[j],'first a[j]')
            else:
                #print(a[j],'a j')
                #print(j,'j')
                
                a_t[j]=a_t[j]-sum([projection(a_t[j],a_t[i]) for i in range(j)]) ### subtract the projections
                
                a_t[j]=(a_t[j]/np.linalg.norm(a_t[j])) ## normalize the vector
                
                #print(a_t[j],'a')
        return a_t.T
                
                
        # * I recommend getting the number of columns (or rows if you prefer to flip the matrix)
        # * make sure your matrix A is cast into floats
        # * begin the top for loop
                #* begin the bottom for loop
                        # * use the projection subtraction here:
                        # remove projection of a[j] over a[i] from a[j]
                # * normalize the column (or row) you're working through
                
        #pass # * return the matrix here. don't rely on pass-by-reference

In [174]:
#stablized_gram_schmidt()

In [175]:
A = np.array([[-2, 0, 1 ],
              [1, -2, 1],
              [1, -1, 0]])

In [176]:
stabilized_gram_schmidt(A)

[[-2  0  1]
 [ 1 -2  1]
 [ 1 -1  0]]
[[-2.  1.  1.]
 [ 0. -2. -1.]
 [ 1.  1.  0.]]


array([[-0.81649658, -0.53452248, -0.21821789],
       [ 0.40824829, -0.80178373,  0.43643578],
       [ 0.40824829, -0.26726124, -0.87287156]])

In [177]:
print([item for item in range(1)])

[0]


In [178]:
B = np.array([[-2,1,1]])

In [179]:
B/np.linalg.norm(B)

array([[-0.81649658,  0.40824829,  0.40824829]])

In [180]:
A = np.array([[-2, 0, 1 ],[1, -2, 1],[1, -1, 0]])
Q = stabilized_gram_schmidt(A)
R = Q.dot(A)

R = Q.T.dot(A)
print(Q,'Q')
print(Q.dot(R))


A = np.array([[-2, 0, 1 ],[1, -2, 1],[1, -1, 0]])

assert np.allclose(Q.dot(R),A)


[[-2  0  1]
 [ 1 -2  1]
 [ 1 -1  0]]
[[-2.  1.  1.]
 [ 0. -2. -1.]
 [ 1.  1.  0.]]
[[-0.81649658 -0.53452248 -0.21821789]
 [ 0.40824829 -0.80178373  0.43643578]
 [ 0.40824829 -0.26726124 -0.87287156]] Q
[[ -2.00000000e+00  -2.42270526e-17   1.00000000e+00]
 [  1.00000000e+00  -2.00000000e+00   1.00000000e+00]
 [  1.00000000e+00  -1.00000000e+00   2.37163747e-16]]


In [160]:
print([item for item in range(0)])

[]
