# DSCI 6001 - 3.3 Lab: LU Factorization II

Today we are going to code up the algorithm that you wrote down yesterday using the scaffold provided below. Simply follow the prompts. 

You might find [this](http://nucinkis-lab.cc.ic.ac.uk/HELM/workbooks/workbook_30/30_3_lu_decomposition.pdf) helpful for reviewing LU decomposition.


In [8]:
import numpy as np
import pprint

In [4]:


def mult_matrix(M, N):
    """Multiply square matrices of same dimension M and N"""
    
    """C = AB - also recall the matrix multiplication formula"""
    
    return C

def pivot_matrix(M):
    """Returns the pivoting matrix P for M, as used in Doolittle's method."""
    m = len(M)

    # *Create an identity matrix, with floating point values. You may use numpy
    
    # id_mat = ?

    # Rearrange the identity matrix such that the largest element of                                                                                                                                                                                   
    # each column of M is placed on the diagonal of of M
    
    # for every row in the input matrix
    for j in xrange(m):
        # *find the row with the biggest element in column j (so we are looking for the diagonal elements M[j,j])
        # *we do not want to be swapping with rows above this one, just the rows below it.
        
        
        if j != row: #if this row is not the row with the next biggest diagonal element
            
            # *Swap the rows of the id matrix                                                

    return id_mat

def LU_decompose(PA, L, U, n):
    """Performs the actual LU decomposition using the standard formula"""
    for j in xrange(n):
        
        # All diagonal entries of L are first set to 1, you may use numpy to do this as well.                                                                                                                                                                                                
        

        # *Encode the following logic:
        # *LaTeX: $u_{ij} = a_{ij} - \sum_{k=1}^{i-1} u_{kj} l_{ik}$                                                                                                                                                                                     
        for i in xrange(j+1):
            pass

        # *Encode the following logic:
        # *LaTeX: $l_{ij} = \frac{1}{u_{jj}} (a_{ij} - \sum_{k=1}^{j-1} u_{kj} l_{ik} )$                                                                                                                                                                  
        for i in xrange(j, n):
            pass
        
        
    return L, U

def lu_decomposition(A):
    """Performs an LU Decomposition of A (which must be square)                                                                                                                                                                                        
    into PA = LU. The function returns P, L and U."""
    n = len(A)

    # * Create zero matrices for L and U or use np.zeros(())                                                                                                                                                                                                                
    # L = ?
    # U = ?

    # Create the pivot matrix P and the matrix product PA                                                                                                                                                                                            
    P = pivot_matrix(A)
    PA = mult_matrix(P, A)
    # Decompose
    L, U = LU_decompose(PA, L, U, n)
    
    return (P, L, U)


A = [[7, 3, -1, 2], [3, 8, 1, -4], [-1, 1, 4, -1], [2, -4, -1, 6]]
P, L, U = lu_decomposition(A)

print("A:")
pprint.pprint(A)

print("P:")
pprint.pprint(P)

print("L:")
pprint.pprint(L)

print("U:")
pprint.pprint(U)

IndentationError: expected an indented block (<ipython-input-4-22e88b440966>, line 32)

In [12]:
import numpy as np
import pprint


def mult_matrix(M, N):
    """Multiply square matrices of same dimension M and N"""
    
    """C = AB - also recall the matrix multiplication formula"""
    if np.shape(M)==np.shape(N):
        C = M.dot(N)
        return C



In [240]:
B =  np.array([[7, 3, -1, 299], [3, 8, 1, -4], [-1, 1, 4, -1], [288, -4, -1, 6]])
C = np.array([[7, 4, -1, 2], [3, 123, 1, -4], [-1, 131, 423, -1], [2123, -4, -1, 6]])

mult_matrix(B,C)

array([[634836,   -930,   -726,   1797],
       [ -8448,   1143,    432,    -51],
       [ -2131,    647,   1695,    -16],
       [ 14743,    505,   -721,    629]])

In [205]:
def pivot_matrix(M):
    """Returns the pivoting matrix P for M, as used in Doolittle's method."""
    m = len(M)

    # *Create an identity matrix, with floating point values. You may use numpy
    
    id_mat = np.identity(m,dtype=float)
    
    # id_mat = ?

    # Rearrange the identity matrix such that the largest element of                                                                                                                                                                                   
    # each column of M is placed on the diagonal of our M
    
    
    
    # for every row in the input matrix
    for j in range(m):
        #print(j)
        
        # *find the row with the biggest element in column j (so we are looking for the diagonal elements M[j,j])
        
        max_number_per_column = max(abs(M[:,j]))
        #print(M[j])
        
        row_number_of_max_number_per_column = [item for item in range(j,(m)) if max_number_per_column in (M[item]) ]

        
        if j != row_number_of_max_number_per_column: #if this row is not the row with the next biggest diagonal element
            # *Swap the rows of the id matrix  
            #a[:,0,0], b[:, 0, 0] = b[:, 0, 0], a[:, 0, 0].copy() #swap
            
            
            if (m-j)>1:
                #print(id_mat[j], ' row j')
                #print(id_mat[row_number_of_max_number_per_column],'row number of max number in column')
            
                #print(id_mat[[j,row_number_of_max_number_per_column]] , ' swapping' )
                
                ##This swaps rows, you need to take a copy of the 
                id_mat[j],id_mat[row_number_of_max_number_per_column] = id_mat[row_number_of_max_number_per_column],id_mat[j].copy()
                #print(id_mat, 'id mat should be swapped')   
            else:
                return id_mat
            ##pass
            # *Swap the rows of the id matrix                                                

    



In [206]:
#print(B)
#print(pivot_matrix(B).dot(B))

pivot_matrix(C)

##Checking it out, it swaps the rows of B

array([[ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  0.]])

$u_{ij} = a_{ij} - \sum_{k=1}^{i-1} u_{kj} l_{ik}$ 

$l_{ij} = \frac{1}{u_{jj}} (a_{ij} - \sum_{k=1}^{j-1} u_{kj} l_{ik} )$ 

In [243]:
def LU_decompose(PA, L, U, n):
    """Performs the actual LU decomposition using the standard formula"""
    L = np.identity(n)
    U = np.zeros(n)
    
    #U = np.zeros(n)
   
        
    for j in range(n):
        #print(j,'j')
        # All diagonal entries of L are first set to 1, you may use numpy to do this as well.                                                                                                                                                                                                

        # *Encode the following logic:
        # *LaTeX: $u_{ij} = a_{ij} - \sum_{k=1}^{i-1} u_{kj} l_{ik}$  
        
        for i in range(j+1): ## for the rows
            s1 =0
            for k in range(i):
                s1 += U[[k],[j]] *L[[i],[k]] 
                   
            U[[i],[j]] = PA[[i],[j]]- s1
            
           
            
            #print(U)
            
            
        # *Encode the following logic:
        # *LaTeX: $l_{ij} = \frac{1}{u_{jj}} (a_{ij} - \sum_{k=1}^{j-1} u_{kj} l_{ik} )$                                                                                                                                                                  
        for i in range(j, n):
            s2=0
            for k in range(j):
                s2 += U[[k],[j]] * L[[i],[k]]
                       
            L[[i],[j]] = (PA[[i],[j]] - s2) / U[[j],[j]]
        
        
    return L, U



In [238]:
# https://www.quantstart.com/articles/LU-Decomposition-in-Python-and-NumPy for the Decomposition

In [244]:
A = np.array([[7, 3, -1, 2], [3, 8, 1, -4], [-1, 1, 4, -1], [2, -4, -1, 6]])
             
def lu_decomposition(A):
    """Performs an LU Decomposition of A (which must be square)                                                                                                                                                                                        
    into PA = LU. The function returns P, L and U."""
    n = len(A)

    # * Create zero matrices for L and U or use np.zeros(())                                                                                                                                                                                                                
    L = np.zeros(n)
    U = np.zeros(n)

    # Create the pivot matrix P and the matrix product PA                                                                                                                                                                                            
    P = pivot_matrix(A)
    PA = mult_matrix(P, A)
    # Decompose
    L, U = LU_decompose(PA, L, U, n)
    
    return (P, Lower, U)



P, L, U = lu_decomposition(A)

print("A:")
pprint.pprint(A)

print("P:")
pprint.pprint(P)

print("L:")
pprint.pprint(L)

print("U:")
pprint.pprint(U)

IndexError: too many indices for array

In [245]:
A

array([[ 7,  3, -1,  2],
       [ 3,  8,  1, -4],
       [-1,  1,  4, -1],
       [ 2, -4, -1,  6]])

In [246]:
A[[0],[0]]

array([7])