# DSCI 6001 - 3.3 Lab: LU Factorization II

Today we are going to code up the algorithm that you wrote down yesterday using the scaffold provided below. Simply follow the prompts. 

You might find [this](http://nucinkis-lab.cc.ic.ac.uk/HELM/workbooks/workbook_30/30_3_lu_decomposition.pdf) helpful for reviewing LU decomposition.


In [1]:
import numpy as np
import pprint

In [2]:
import numpy as np
import pprint


def mult_matrix(M, N):
    """Multiply square matrices of same dimension M and N"""
    
    """C = AB - also recall the matrix multiplication formula"""
    if np.shape(M)==np.shape(N):
        C = M.dot(N)
        return C



In [3]:
B =  np.array([[7, 3, -1, 299], [3, 8, 1, -4], [-1, 1, 4, -1], [288, -4, -1, 6]])
C = np.array([[7, 4, -1, 2], [3, 123, 1, -4], [-1, 131, 423, -1], [2123, -4, -1, 6]])

mult_matrix(B,C)

array([[634836,   -930,   -726,   1797],
       [ -8448,   1143,    432,    -51],
       [ -2131,    647,   1695,    -16],
       [ 14743,    505,   -721,    629]])

In [4]:
def pivot_matrix(M):
    """Returns the pivoting matrix P for M, as used in Doolittle's method."""
    m = len(M)

    # *Create an identity matrix, with floating point values. You may use numpy
    
    id_mat = np.identity(m,dtype=float)
    
    # id_mat = ?

    # Rearrange the identity matrix such that the largest element of                                                                                                                                                                                   
    # each column of M is placed on the diagonal of our M
    
    
    
    # for every row in the input matrix
    for j in range(m):
        #print(j)
        
        # *find the row with the biggest element in column j (so we are looking for the diagonal elements M[j,j])
        
        max_number_per_column = max(abs(M[:,j]))
        #print(M[j])
        
        row_number_of_max_number_per_column = [item for item in range(j,(m)) if max_number_per_column in (M[item]) ]

        
        if j != row_number_of_max_number_per_column: #if this row is not the row with the next biggest diagonal element
            # *Swap the rows of the id matrix  
            #a[:,0,0], b[:, 0, 0] = b[:, 0, 0], a[:, 0, 0].copy() #swap
            
            
            if (m-j)>1:
                #print(id_mat[j], ' row j')
                #print(id_mat[row_number_of_max_number_per_column],'row number of max number in column')
            
                #print(id_mat[[j,row_number_of_max_number_per_column]] , ' swapping' )
                
                ##This swaps rows, you need to take a copy of the 
                id_mat[j],id_mat[row_number_of_max_number_per_column] = id_mat[row_number_of_max_number_per_column],id_mat[j].copy()
                #print(id_mat, 'id mat should be swapped')   
            else:
                return id_mat
            ##pass
            # *Swap the rows of the id matrix                                                

    



In [5]:
#print(B)
#print(pivot_matrix(B).dot(B))

pivot_matrix(C)

##Checking it out, it swaps the rows of B

array([[ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  0.]])

$u_{ij} = a_{ij} - \sum_{k=1}^{i-1} u_{kj} l_{ik}$ 

$l_{ij} = \frac{1}{u_{jj}} (a_{ij} - \sum_{k=1}^{j-1} u_{kj} l_{ik} )$ 

In [6]:
## this seems to work for the equations presented above

def LU_decompose(PA, L, U, n):
    """Performs the actual LU decomposition using the standard formula"""
    L = np.identity(n)
    U = np.zeros(shape=(n,n))
    
    print(L,U)
    #U = np.zeros(n)

    for j in range(n): ### number of rows
        #print(j,'j')
        # All diagonal entries of L are first set to 1, you may use numpy to do this as well.                                                                                                                                                                                                

        # *Encode the following logic:
        # *LaTeX: $u_{ij} = a_{ij} - \sum_{k=1}^{i-1} u_{kj} l_{ik}$  
        print(j,'j')
        for i in range(j+1): ## for the columns ( include j)
            s1=0
            print(j+1,'j+1')
            for k in range(i):
                print(i,'i')
                print(k,'k')
                print()
                print(U[[k],[j]], "U[[k],[j]]")
                print((L[[i],[k]]),'L')
                s1+=(U[[k],[j]] *L[[i],[k]])
                
            print(A[[i],[j]], 'A[[i],[j]]')
            
            U[[i],[j]] =( PA[[i],[j]]- s1)

            
        # *Encode the following logic:
        # *LaTeX: $l_{ij} = \frac{1}{u_{jj}} (a_{ij} - \sum_{k=1}^{j-1} u_{kj} l_{ik} )$                                                                                                                                                                  
        for i in range(j, n):

            s2 = sum([(U[[k],[j]] * L[[i],[k]]) for k in range(j)])
                

            L[[i],[j]] = (PA[[i],[j]] - s2) / U[[j],[j]]
        
        
    return L, U



In [8]:
C[[1],[0]]

array([3])

In [9]:
A = np.array([[7, 3, -1, 2], [3, 8, 1, -4], [-1, 1, 4, -1], [2, -4, -1, 6]])
             
def lu_decomposition(A):
    """Performs an LU Decomposition of A (which must be square)                                                                                                                                                                                        
    into PA = LU. The function returns P, L and U."""
    n = len(A)

    # * Create zero matrices for L and U or use np.zeros(())                                                                                                                                                                                                                
    L = np.zeros(n)
    U = np.zeros(n)

    # Create the pivot matrix P and the matrix product PA                                                                                                                                                                                            
    P = pivot_matrix(A)
    PA = mult_matrix(P, A)
    # Decompose
    L, U = LU_decompose(PA, L, U, n)
    
    return (P, L, U)



P, L, U = lu_decomposition(A)

print("A:")
pprint.pprint(A)

print("P:")
pprint.pprint(P)

print("L:")
pprint.pprint(L)

print("U:")
pprint.pprint(U)

print(L.dot(U))

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]] [[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
0 j
1 j+1
[7] A[[i],[j]]
1 j
2 j+1
[3] A[[i],[j]]
2 j+1
1 i
0 k

[ 3.] U[[k],[j]]
[ 0.42857143] L
[8] A[[i],[j]]
2 j
3 j+1
[-1] A[[i],[j]]
3 j+1
1 i
0 k

[-1.] U[[k],[j]]
[ 0.42857143] L
[1] A[[i],[j]]
3 j+1
2 i
0 k

[-1.] U[[k],[j]]
[-0.14285714] L
2 i
1 k

[ 1.42857143] U[[k],[j]]
[ 0.21276596] L
[4] A[[i],[j]]
3 j
4 j+1
[2] A[[i],[j]]
4 j+1
1 i
0 k

[ 2.] U[[k],[j]]
[ 0.42857143] L
[-4] A[[i],[j]]
4 j+1
2 i
0 k

[ 2.] U[[k],[j]]
[-0.14285714] L
2 i
1 k

[-4.85714286] U[[k],[j]]
[ 0.21276596] L
[-1] A[[i],[j]]
4 j+1
3 i
0 k

[ 2.] U[[k],[j]]
[ 0.28571429] L
3 i
1 k

[-4.85714286] U[[k],[j]]
[-0.72340426] L
3 i
2 k

[ 0.31914894] U[[k],[j]]
[ 0.08982036] L
[6] A[[i],[j]]
A:
array([[ 7,  3, -1,  2],
       [ 3,  8,  1, -4],
       [-1,  1,  4, -1],
       [ 2, -4, -1,  6]])
P:
array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],


In [10]:
assert(L.dot(U).all()==A.all())

In [11]:
A[[0],[0]]

array([7])