### DSCI6001 2.1 Lab

This will be a graded laboratory assignment of approximately 30 minutes.

Review [numpy.linalg.solve](http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.linalg.solve.html). 

1) Create matrices representing the linear systems in Kreyszig Chapter 7 (9th ed. page 330) problems 12, 14, 16, 18.
      

In [44]:
import numpy as np
twelve = np.asarray([[-2,-4,7],
                    [1,2,16]])
twelve_b = np.asarray([[-6],
                      [3]])
fourteen = np.asarray([[5, -10],
                      [3,1],
                      [-1,6]])
fourteen_b = np.asarray([[2],
                        [13],
                        [6]])
sixteen = np.asarray([[0,2,1],
                     [2,3,-1],
                     [5,-4,3]])
sixteen_b = np.asarray([[-1],
                      [-12],
                      [32]])
eighteen = np.array([[-1.,4.,-2.],
                      [3.,4.,6.],
                      [1.,-2.,2.]])
eighteen_b = np.array([[1],
                        [1],
                        [-.5]])

2) Confirm the shapes of the coefficient matrices, by inspection or using Python. Which of these can numpy solve? Use numpy to solve the systems it can solve. Explain the solution set to the systems numpy cannot solve.
   

In [68]:
print(np.shape(twelve),"Numpy can't solve this, not a nxn matrix, underdetermined")
print(np.shape(fourteen),"Numpy can't solve this, not a nxn matrix")
print(np.shape(sixteen), "Numpy can solve this because it is a nxn matrix")
print(np.shape(eighteen), "Numpy can solve this because it is a nxn matrix")


(2, 3) Numpy can't solve this, not a nxn matrix, underdetermined
(3, 2) Numpy can't solve this, not a nxn matrix
(3, 3) Numpy can solve this because it is a nxn matrix
(3, 3) Numpy can solve this because it is a nxn matrix


Since number sixteen and eighteen are square matrices, the next step is to check the determinants of each.

In [53]:
print(np.linalg.det(sixteen)) ## determinant of sixteen exists
print(np.allclose(np.linalg.det(sixteen),0)) #Not close to zero


-45.0
False


In [142]:
print(np.linalg.det(eighteen))
print(np.allclose(np.linalg.det(eighteen),0)) ### this determinant is being treated as zero, for this question there are infinite solution
#print(np.linalg.rank(eighteen))

-1.7763568394e-15
True


For matrix eighteen, r < n , so there are infinite solutions

In [47]:
print(np.linalg.solve(sixteen,sixteen_b))


[[ 1.]
 [-3.]
 [ 5.]]


The only linear system we can solve is number sixteen since the determinant of problem eighteen is treated as zero.

3) Create numpy  matrices A and B, and vectors a, b from Kreyszig Chapter 7 (9th ed. page 331). Using Python, calculate:
* AB, BA
* $\textit{A}\textit{A}^{T}$
* $\textit{B}^{T}\textit{A}$
* $\textit{a}^{T}\textit{b}$
* $\textit{b}^{T}\textit{a}$
* $\textit{ab}^{T}$    
* $\textit0.1({A}+{A}^{T})({B}-{B}^{T})$

In [18]:
A = np.array([[9,2,8],
             [2,18,10],
             [8,10,15]])
B = np.array([[0,2,6],
             [-2,0,-3],
             [-6,3,0]])
a = np.array([[3],
             [7],
             [1]])
b = np.array([[4],
             [0],
             [2]])



In [31]:
print(A.dot(B) ," A.dot(B) ", B.dot(A),"B.dot(A)")
print(A.dot(A.T),"A.dot(A.T)")
print(B.T.dot(A),"B.T.dot(A)")
print(a.T.dot(b),"a.T.dot(b)")
print(b.T.dot(a),'b.T.dot(a)')
print(a.dot(b.T),'a.dot(b.T)')
print((.1*(A+A.T)).dot(B-B.T), '(.1*(A+A.T)).dot(B-B.T)')

[[ -52   42   48]
 [ -96   34  -42]
 [-110   61   18]]  A.dot(B)  [[ 52  96 110]
 [-42 -34 -61]
 [-48  42 -18]] B.dot(A)
[[149 134 212]
 [134 428 346]
 [212 346 389]] A.dot(A.T)
[[ -52  -96 -110]
 [  42   34   61]
 [  48  -42   18]] B.T.dot(A)
[[14]] a.T.dot(b)
[[14]] b.T.dot(a)
[[12  0  6]
 [28  0 14]
 [ 4  0  2]] a.dot(b.T)
[[-20.8  16.8  19.2]
 [-38.4  13.6 -16.8]
 [-44.   24.4   7.2]] (.1*(A+A.T)).dot(B-B.T)


4) According to the [Pew Research Center](http://www.pewsocialtrends.org/2015/12/09/the-american-middle-class-is-losing-ground/), America in 1970 was 10% lower, 62% middle, and 28% upper class. Create a simple Markov process to model the decades from 1970 to 2070, using the following estimates that per decade... 
* Lower class has a 5% chance of becoming middle class, 1% of upper class
* Middle class has a 10% chance of lower class, and a 5% chance upper class
* Upper class: 5% chance become lower class, 10% become middle class

In [137]:
#set up transition matrix
#multiply transition matrix by current state 
#iterate through (10 times) until you get to 2070
transition_matrix =np.array([[.94,.05,.01], #first row is the lower class probability of transition to lower , middle high
                            [.1,.85,.05], #second row is the middle class probability of transition to lower, middle, high
                            [.05,.1,.85]]) #third row is upper class probability of transition to lower, middle, high

current_state = np.array([[.10],
                         [.62],
                         [.28]])


In [138]:
print(sum(current_state))

sum(transition_matrix.dot(current_state))

[ 1.]


array([ 0.9838])

In [140]:


for i in range(1, 11):
    print('In ', i, 'decades, we have:')
    print(np.linalg.matrix_power(transition_matrix.T,i).dot(current_state),"proportion of Low, Middle, High")
    
    #print(sum(np.linalg.matrix_power(transition_matrix.T,i).dot(current_state)))


In  1 decades, we have:
[[ 0.17]
 [ 0.56]
 [ 0.27]] proportion of Low, Middle, High
In  2 decades, we have:
[[ 0.2293]
 [ 0.5115]
 [ 0.2592]] proportion of Low, Middle, High
In  3 decades, we have:
[[ 0.279652]
 [ 0.47216 ]
 [ 0.248188]] proportion of Low, Middle, High
In  4 decades, we have:
[[ 0.32249828]
 [ 0.4401374 ]
 [ 0.23736432]] proportion of Low, Middle, High
In  5 decades, we have:
[[ 0.35903034]
 [ 0.41397814]
 [ 0.22699152]] proportion of Low, Middle, High
In  6 decades, we have:
[[ 0.39023591]
 [ 0.39253209]
 [ 0.21723201]] proportion of Low, Middle, High
In  7 decades, we have:
[[ 0.41693656]
 [ 0.37488727]
 [ 0.20817617]] proportion of Low, Middle, High
In  8 decades, we have:
[[ 0.4398179 ]
 [ 0.36031862]
 [ 0.19986347]] proportion of Low, Middle, High
In  9 decades, we have:
[[ 0.45945387]
 [ 0.34824807]
 [ 0.19229806]] proportion of Low, Middle, High
In  10 decades, we have:
[[ 0.47632634]
 [ 0.33821336]
 [ 0.18546029]] proportion of Low, Middle, High


In [121]:
#class_transition(transition_matrix,current_state,10)