## LU Decomposition Lab
Do the following by hand.

We will follow the general structure we outlined in the lecture

Given $A{\bf x} = b$ and $A = LU$:

0. Check for decomposability, pivot if necessary
1. Decompose A into L and U.
2. Let $L{\bf y} = b$. 
3. Solve for ${\bf y}$.
5. Recall ${\bf y} = U{\bf x}$.
6. Solve this equation to get ${\bf x}$.

## Problem
$$\begin{bmatrix} 1 & 6 & 2 \\ 2 & 12 & 5 \\ -1 & -3 & -1 \end{bmatrix}
\begin{bmatrix} x_{0} \\ x_{1} \\ x_{2} \end{bmatrix} = \begin{bmatrix} 9 \\ -4 \\ 17 \end{bmatrix}$$



### LU Decomposition
#### Check for decomposability (Step 1)
Write out the submatrices for $A$. You should have an $A_{1}$, $A_{2}$, and $A_{3}$.

$A_{1}$ = 1 Det(1) = 1
$A_{2}$ = [ 1 , 6] , [2, 12]  det ($A_{2}$ ) = 0


What are the determinants for each submatrix? 

Can $A$ be decomposed in the current state?

$A$ can NOT be decomposed in the current state.



#### Pivot (Step 1)
Swap rows in $A$. Check the result for decomposability again. Once you've found a swap that works, move on to the next step.

We need to swap the following first becomes second, second becomes third, third becomes first.

B = $$\begin{bmatrix} -1 & -3 & -1\\ 1 & 6 & 2 \\2 & 12 & 5  \end{bmatrix}$$


In [121]:
L.dot(U)

array([[1, 3, 1],
       [1, 4, 1],
       [2, 8, 3]])

In [3]:
import numpy as np
B = np.asarray([[-1,-3,-1],
          [1,6,2],
          [2,12,5]])

np.linalg.det(B)

-2.9999999999999996

#### Form (Step 2)
Write out the L and U matrices using variables ($A_{ij}$, $L_{ij}$, $U_{ij}$) and 1s/0s where necessary.

$A_{11} = U_{11}$

$A_{12} = U_{12}$

$A_{13} = U_{13}$

$A_{21} = L_{21} * U_{11}$

$A_{22} = L_{21} * U_{12} + U_{22}$

$A_{23} = L_{21} * U_{13} + U_{23}$

$A_{31} = L_{31} * U_{11}$

$A_{32} = L_{31} * U_{12} + L_{32} * U_{22}$

$A_{33} = L_{31} * U_{13} + L_{32} * U_{23} + U_{33}$


#### Equations (Step 2)
Write out $A = LU$ in a component by component basis. You should end up with a series of equations based on matrix multiplication.  
Ex. $A_{11} = 1 * U_{11}$



B11 =** U11  = -1**

B12 = ** U12 = -3**

B13 =** U13 = -1**

B21 = L21 $*$ U11 => 1 = L21 $*$ -1 => **L21 = -1 **

B22 = L21 $*$ U12 + U22 => -1 $*$ -3 + U22 = 6  => **U22 = 3**

B23 = L21 $*$ U13 + U23 => -1 $*$ -1 + U23 = 2 => **U23 = 1**

B31 = L31 $*$ U11 => L31 $*$ -1 = 2 => ** L31 = -2**

B32 = L31 $*$U12 + L32 $*$ U22 => -2 $*$ -3 + L32 $*$ 3 = 12 =>  **L32 = 2**

B33 = L31 $*$ U13 + L32 $*$ U23 + U33 =>  -2 $*$ -1 + 2 $*$ 1 + U33 = 5 => **U33 =1 **






#### Solve the equations above for all variables (Step 2)
Solve for each varaible. What are the final L and U matrices?

L = $$\begin{bmatrix} 1 & 0 & 0\\ -1 & 1 & 0 \\-2 & 2 & 1  \end{bmatrix}$$

U = $$\begin{bmatrix} -1 & -3 & -1\\ 0 & 3 & 1 \\ 0& 0 & 1  \end{bmatrix}$$


### Solving the system
#### Solve for ${\bf y}$ (Step 3/4)
Next, we set $L{\bf y} = b$.  
Plug in your $L$ matrix and $b$.  
You should be able to solve this system of equations for ${\bf y}$.



In [153]:
import numpy as np
#Here PA = LU
#
L = np.asarray([[1,0,0],
                [-1,1,0],
                [-2,2,1]])

U = np.asarray([[-1,-3,-1],
               [0,3,1],
               [0,0,1]])

b = np.asarray([[9],[-4],[17]])


P = np.array([[0,0,1],
                  [1,0,0],
                  [0,1,0]])

b = P.dot(b)

              
y = np.linalg.solve(L,b)
              
y

array([[ 17.],
       [ 26.],
       [-22.]])

In [139]:
#This should equal your PA
L.dot(U)

array([[-1, -3, -1],
       [ 1,  4,  1],
       [ 2,  8,  3]])

#### Solve for ${\bf x}$ (Step 5/6)
Now that we have $y$, recall that $U{\bf x} = {\bf y}$.  
Plug in your $U$ and ${\bf y}$ from above.  
You should be able to solve for ${\bf x}$.

In [159]:
answer_vector  = np.linalg.solve(U,y) ## This is the solutions
answer_vector

array([[-43.],
       [ 16.],
       [-22.]])

In [162]:
original = np.array([[1,6,2],
                    [2,12,5],
                    [-1,-3,-1]])
original_vector = np.array([[9],
                           [-4],
                           [17]])

In [164]:
np.linalg.solve(original,original_vector)

array([[-43.],
       [ 16.],
       [-22.]])

In [165]:
#The solutions match so the answer is correct