# RAT 4.1

1. Describe the three component matrices of an SVD.
2. What special properties do the three component matrices have?
3. Use numpy (not linalg.svd) to calculate a solution to the SVD of $A = \begin{bmatrix}1 & -1\\3 & 1\end{bmatrix}$. You will need to use linalg.eig.

# Question One

The three parts of SVD are** $ U * D * V . T$** = A

- U - represents the feature space of the matrix. To find the U matrix, you take $A * A. T$ to preseve the number of rows in the matrix. Next, you find the eigenvalues and eigenvectors for U. Then, you take the eigenvectors to create the matrix U.

- D contains the eigenvalues of A along the diagonal of the matrix. Usually, you will normalize these eigenvalues. The rest of the values of the matrix contain zero, but it is important that each eigenvalue goes into the space on the diagonal that corresponds to the eigenvectors in U and V. If you have fewer eigenvalues that

- V represents the sample space of the matrix. To find the V matrix, you take $ A.T * A $ which will preseve the number of columns in the matrix. Next, you use the eigenvalues you found for matrix U to find the eigenvectors for your V matrix (using the $ A.T * A $ that was computed). After, you place these eigenvectors together to form matrix V, which you usually normalize, make sure that each eigenvector corresponds to the correct eigenvalue. After, you take the transpose of V for the SVD multiplication.

# Question Two

- U spans the feature space of matrix A

- V spans the sample space of matrix A

- D contains the eigenvalues of matrix A which tell you the magnitude of your transformation.

In [89]:
import numpy as np
A = np.array([[1,-1],
             [3,1]])

In [104]:
U  = A.dot(A.T)

In [105]:
U

array([[ 2,  2],
       [ 2, 10]])

In [92]:
V = A.T.dot(A)

In [106]:
U = np.linalg.eig(U)[1]
U

array([[-0.97324899, -0.22975292],
       [ 0.22975292, -0.97324899]])

In [107]:
U[0][0] , U[1][0] = U[0][1]  , U[1][1].copy()


In [108]:
U

array([[-0.22975292, -0.22975292],
       [-0.97324899, -0.97324899]])

In [96]:
np.linalg.eig(V)

(array([ 10.47213595,   1.52786405]), array([[ 0.97324899, -0.22975292],
        [ 0.22975292,  0.97324899]]))

In [97]:
V = np.linalg.eig(V)[1]

In [98]:
#np.linalg.eigvals(V)[0]
D = np.array([[V[0][0],0],
             [0,V[1][1]]])

In [99]:
D

array([[ 0.97324899,  0.        ],
       [ 0.        ,  0.97324899]])

In [100]:
U.dot(D).dot(V.T)

array([[-0.16625078, -0.2689994 ],
       [-0.70424958, -1.13949976]])

In [103]:
np.linalg.svd(A.dot(A.T))

(array([[ 0.22975292,  0.97324899],
        [ 0.97324899, -0.22975292]]),
 array([ 10.47213595,   1.52786405]),
 array([[ 0.22975292,  0.97324899],
        [ 0.97324899, -0.22975292]]))