# DSCI6001 4.4 Lab  

## Recursive calculation of the determinant

(This is a graded lab assignment)

Today you will calculate the determinant recursively using the skills you developed yesterday. You should be familiar enough to jump into writing the algorithm essentially from scratch. 

The determinant is easily calculated using the Laplace expansion:

$$det(A) = \sum_{i=1}^{N} (-1)^{i+1} A_{i,1} det(C_{i})$$

where $C_{i,1}$ is the $(n-1) \times (n-1)$ matrix obtained from A by removing (deleting) the i-th row and first column. (The first column does not play a special role here: the determinant remains the same if we use any other column.) 

Note that the stopping condition in this case for the determinant function is the determinant of size $2 \times 2$. Yes, you can consider expansions that end in the $1 \times 1$ expansion. Just make sure your math is right. 

Your code should be able to pass the simple test harness provided below.
Our solution was written in 11 lines. You might consider making use of the `numpy.delete` function (make sure to test it out to understand it). Our other comment is to take advantage of simple sums where you can. Remember that each determinant is a sum over columns !!!

In [296]:
def det(x):
    
    # you might consider making a `minor` function to help you calculate the minor matrices 
    sum_of_determinants=0
    minors = []
    print(sum_of_determinants,'sum det')
    
    def minor(x, rows, columns):
        rows = rows
        columns = columns
        x = np.delete(x,0,axis=0) ##delete the first row
        x = np.delete(x,columns,1) ## delete the columns
        
        return x

    rows=x.shape[0]
    #print(rows,'rows'
    columns = x.shape[1]
    #print(columns,'columns')
    print(x,'matrix')
    print(x.shape,'x shape')
    
    if x.shape ==(2,2):
        
        print('base case')
        #sum_of_determinants += (x[0,0] *x[1,1] ) - (x[0,1]*x[1,0])
        
        return (x[0,0] *x[1,1] ) - (x[0,1]*x[1,0])
    
    else:
        print(sum_of_determinants, ' sum else case')
    
        #for count, item in enumerate(rows):
        for item in range(rows):
            
            #minors += minor(x,item,item)
            return sum([(det(minor(x,item,item))*x[0,item]*(-1)**(rows+columns)) for item in range(0,rows)])
    
    #return sum(sum_of_determinants)
    # recursion goes here. You'll need to define the base case first!! In every other case, 
    # you're returning a sum!
    


In [320]:
B = np.array([[1,34,0],
             [0,5,345],
             [0,45,3]])

In [321]:
det(B)

0 sum det
[[  1  34   0]
 [  0   5 345]
 [  0  45   3]] matrix
(3, 3) x shape
0  sum else case
0 sum det
[[  5 345]
 [ 45   3]] matrix
(2, 2) x shape
base case
0 sum det
[[  0 345]
 [  0   3]] matrix
(2, 2) x shape
base case
0 sum det
[[ 0  5]
 [ 0 45]] matrix
(2, 2) x shape
base case


-15510

In [322]:
np.linalg.det(B)

-15509.999999999995

In [323]:
# Here is a simple test harness

import numpy as np
import copy
import numpy.linalg as LA
    


In [324]:
for i in range(20):
    X = np.random.randint(5, size=(6,6))
    assert np.isclose(float(det(X)), LA.det(X))

0 sum det
[[2 4 4 0 2 1]
 [1 3 2 4 4 4]
 [4 2 0 3 3 4]
 [4 3 1 1 2 4]
 [4 3 1 1 4 0]
 [3 1 3 3 0 2]] matrix
(6, 6) x shape
0  sum else case
0 sum det
[[3 2 4 4 4]
 [2 0 3 3 4]
 [3 1 1 2 4]
 [3 1 1 4 0]
 [1 3 3 0 2]] matrix
(5, 5) x shape
0  sum else case
0 sum det
[[0 3 3 4]
 [1 1 2 4]
 [1 1 4 0]
 [3 3 0 2]] matrix
(4, 4) x shape
0  sum else case
0 sum det
[[1 2 4]
 [1 4 0]
 [3 0 2]] matrix
(3, 3) x shape
0  sum else case
0 sum det
[[4 0]
 [0 2]] matrix
(2, 2) x shape
base case
0 sum det
[[1 0]
 [3 2]] matrix
(2, 2) x shape
base case
0 sum det
[[1 4]
 [3 0]] matrix
(2, 2) x shape
base case
0 sum det
[[1 2 4]
 [1 4 0]
 [3 0 2]] matrix
(3, 3) x shape
0  sum else case
0 sum det
[[4 0]
 [0 2]] matrix
(2, 2) x shape
base case
0 sum det
[[1 0]
 [3 2]] matrix
(2, 2) x shape
base case
0 sum det
[[1 4]
 [3 0]] matrix
(2, 2) x shape
base case
0 sum det
[[1 1 4]
 [1 1 0]
 [3 3 2]] matrix
(3, 3) x shape
0  sum else case
0 sum det
[[1 0]
 [3 2]] matrix
(2, 2) x shape
base case
0 sum det
[[1 0]
 [3 

AssertionError: 

In [9]:
A = np.array([[1,2,5],
             [4,58,45],
             [1,5,3]])

In [143]:
np.delete(A,2,1)

array([[ 1,  2],
       [ 4, 58],
       [ 1,  5]])

In [113]:
A[0,1]

2