# DSCI6001 1.4.Lab (Graded)

This will be a graded laboratory assignment of approximately 30 minutes.

In yesterday's lecture you were assigned from Kreyszig 9th ed.

#### Reading 
* 7.4, 7.5, 7.7

#### Problems 
* 7.4: 1, 3, 7, 11, 15, 19, 27, 33, 35
* 7.7: 5, 7, 11, 14, 19, 21

If you have completed the above assigments, you may proceed with the lab.

## Lab

Solve using Python. Hint: search the numpy documentation.

1. Write a Python function `randomat` that returns a random square numpy matrix of integers of given dimension n. The integers should be between -1 and 3. 

2. Create a list containing 50 `randomat` 3x3 matrices. Make a copy of the list, in the form of a Pandas `Series`. Hint: Solution provided below.

3. Create a list of the the 50 *determinants* of the 50 matrices. Make a copy of the list, in the form of a Pandas `Series`.

4.  Create a list of the the 50 *ranks* of the 50 matrices. Make a copy of the list, in the form of a Pandas `Series`.

5. Extract two suitable matrices from your array into variables A and B, then write assertions to test the following Inversion Properties:

    1. $({\bf A}^{-1})^{-1} = {\bf A}$
    2. $({\bf AB})^{-1} = {\bf B}^{-1} {\bf A}^{-1}$  Hint: Solution below
    3. $|{\bf AB}| = |{\bf A}| ~ |{\bf B}| = |{\bf BA}|$
    4. $|{\bf A}^T| = |{\bf A}|$
    5. $|{\bf A}^{-1}| = \frac{1}{|{\bf A}|}$
    
6. Exactly how many of your randomly generated matrices were unsuitable for exercise 5. What makes them unsuitable? 


In [68]:
import numpy as np

def randomat(dimension):
    #B= np.asarray([[]])

    return np.asarray([[np.random.randint(-1,3) for item in range(dimension)] for item in range(dimension)])
    
    #return B
    
a = np.random.randint(-1,3)

randomat(2)

array([[ 1,  1],
       [-1,  1]])

# Question Two
Create a list containing 50 randomat 3x3 matrices. Make a copy of the list, 
in the form of a Pandas Series. Hint: Solution provided below.

In [69]:
import pandas as pd

# 2. You can use a for loop, or here is a solution using a list comprehension
matrix_list = [randomat(3) for _ in range(50)]

# Convert the list into a Series. Both forms have their uses.
matrix_Series = pd.Series (matrix_list)

print(matrix_Series.head())


0     [[2, 0, 1], [-1, 1, 1], [2, 2, -1]]
1    [[-1, 1, -1], [-1, 1, 0], [2, 2, 0]]
2       [[2, 1, 0], [2, 1, 0], [2, 1, 2]]
3       [[2, 0, 0], [2, 0, 1], [2, 1, 0]]
4      [[2, 0, -1], [1, 2, 0], [2, 2, 0]]
dtype: object


# Question Three
Create a list of the the 50 determinants of the 50 matrices. Make a copy of the list, in the form of a Pandas Series.

In [70]:
matrix_determinants = [np.linalg.det(a) for a in matrix_Series]
#print(matrix_determinants)
matrix_determinants_Series = pd.Series(matrix_determinants)

# Question Four
Create a list of the the 50 ranks of the 50 matrices. Make a copy of the list, in the form of a Pandas Series.

In [71]:
matrix_rank = [np.linalg.matrix_rank(a) for a in matrix_Series]
#print(matrix_rank)
matrix_rank_Series = pd.Series(matrix_rank)

In [72]:
from numpy.linalg import det, inv
from numpy import allclose
#assert np.allclose(inv(A.dot(B)), Binv.dot(Ainv))



# Question Five
5. Extract two suitable matrices from your array into variables A and B, then write assertions to test the following Inversion Properties:

    1. $({\bf A}^{-1})^{-1} = {\bf A}$
    2. $({\bf AB})^{-1} = {\bf B}^{-1} {\bf A}^{-1}$  Hint: Solution below
    3. $|{\bf AB}| = |{\bf A}| ~ |{\bf B}| = |{\bf BA}|$
    4. $|{\bf A}^T| = |{\bf A}|$
    5. $|{\bf A}^{-1}| = \frac{1}{|{\bf A}|}$
    

In [131]:
A = matrix_list[0]
B = matrix_list[5]
print(type(A),B)
print(np.shape(A))

<class 'numpy.ndarray'> [[ 1 -1  2]
 [ 0 -1  1]
 [ 1 -1 -1]]
(3, 3)


In [149]:

assert inv(inv(A)).all() == A.all() ##Property one
assert inv(A.dot(B)).all() == inv(B).dot(inv(A)).all() ## property two

R = det(B.dot(A))
S = det(A)*det(B)
T = det(A.dot(B))
#print(R,S,T)
assert np.allclose(R,S) ## Property three 
assert np.allclose(S,T)## Property three
assert np.allclose(R,T) ## Property three

assert np.allclose((det(A.T)), det(A)) #Property four

assert np.allclose(det(inv(A)),1/det(A)) #Property five
print('All tests pass!')


All tests pass!


# Question Six
Exactly how many of your randomly generated matrices were unsuitable for exercise 5. What makes them unsuitable?
In [68]:

)
import numpy as np

In [158]:
def non_zero_det (matrix_list):
    for count,matrix in enumerate(matrix_list):
        B = np.asarray([[1,3],
                       [1,2]])
        counter = 0 
        try:
            assert inv(inv(matrix_list[count])).all() == (matrix_list[count]).all() ##Property one
            assert inv((matrix_list[count]).dot(B)).all() == inv(B).dot(inv(matrix_list[count])).all() ## property two

            R = det(B.dot((matrix_list[count])))
            S = det((matrix_list[count]))*det(B)
            T = det((matrix_list[count]).dot(B))
            #print(R,S,T)
            assert np.allclose(R,S) ## Property three 
            assert np.allclose(S,T)## Property three
            assert np.allclose(R,T) ## Property three

            assert np.allclose((det((matrix_list[count]).T)), det((matrix_list[count]))) #Property four

            assert np.allclose(det(inv((matrix_list[count]))),1/det((matrix_list[count]))) #Property five
            print('All tests pass!')
        except:
            counter +=1

    return('This number of matrices failed because their determinant ==0: ',count)
non_zero_det(matrix_list)

('This number of matrices failed because their determinant ==0: ', 49)